import logging
import mimetypes
import zipfile
from pathlib import Path
from urllib.parse import quote

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, PlainTextResponse, Response

from app.gateway.authz import require_permission
from app.gateway.path_utils import resolve_thread_virtual_path

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["artifacts"])

ACTIVE_CONTENT_MIME_TYPES = {
    "text/html",
    "application/xhtml+xml",
    "image/svg+xml",
}

MAX_SKILL_ARCHIVE_MEMBER_BYTES = 16 * 1024 * 1024
_SKILL_ARCHIVE_READ_CHUNK_SIZE = 64 * 1024


def _build_content_disposition(disposition_type: str, filename: str) -> str:
    """构建符合 RFC 5987 编码的 Content-Disposition 响应头值。"""
    return f"{disposition_type}; filename*=UTF-8''{quote(filename)}"


def _build_attachment_headers(filename: str, extra_headers: dict[str, str] | None = None) -> dict[str, str]:
    headers = {"Content-Disposition": _build_content_disposition("attachment", filename)}
    if extra_headers:
        headers.update(extra_headers)
    return headers


def is_text_file_by_content(path: Path, sample_size: int = 8192) -> bool:
    """通过检查内容中是否含有空字节来判断文件是否为文本文件。"""
    try:
        with open(path, "rb") as f:
            chunk = f.read(sample_size)
            # 文本文件不应包含空字节
            return b"\x00" not in chunk
    except Exception:
        return False


def _read_skill_archive_member(zip_ref: zipfile.ZipFile, info: zipfile.ZipInfo) -> bytes:
    """读取 .skill 压缩包中的成员，并强制限制解压后的大小上限。"""
    if info.file_size > MAX_SKILL_ARCHIVE_MEMBER_BYTES:
        raise HTTPException(status_code=413, detail="Skill archive member is too large to preview")

    chunks: list[bytes] = []
    total_read = 0
    with zip_ref.open(info, "r") as src:
        while chunk := src.read(_SKILL_ARCHIVE_READ_CHUNK_SIZE):
            total_read += len(chunk)
            if total_read > MAX_SKILL_ARCHIVE_MEMBER_BYTES:
                raise HTTPException(status_code=413, detail="Skill archive member is too large to preview")
            chunks.append(chunk)
    return b"".join(chunks)


def _extract_file_from_skill_archive(zip_path: Path, internal_path: str) -> bytes | None:
    """从 .skill ZIP 压缩包中提取文件。

    Args:
        zip_path: .skill 文件（ZIP 压缩包）的路径。
        internal_path: 压缩包内文件的路径（例如 "SKILL.md"）。

    Returns:
        文件内容的字节数据，未找到时返回 None。
    """
    if not zipfile.is_zipfile(zip_path):
        return None

    try:
        with zipfile.ZipFile(zip_path, "r") as zip_ref:
            # 列出压缩包中的所有文件
            infos_by_name = {info.filename: info for info in zip_ref.infolist()}

            # 先尝试直接匹配路径
            if internal_path in infos_by_name:
                return _read_skill_archive_member(zip_ref, infos_by_name[internal_path])

            # 再尝试带任意顶层目录前缀的路径（例如 "skill-name/SKILL.md"）
            for name, info in infos_by_name.items():
                if name.endswith("/" + internal_path) or name == internal_path:
                    return _read_skill_archive_member(zip_ref, info)

            # 未找到
            return None
    except (zipfile.BadZipFile, KeyError):
        return None


@router.get(
    "/threads/{thread_id}/artifacts/{path:path}",
    summary="Get Artifact File",
    description="Retrieve an artifact file generated by the AI agent. Text and binary files can be viewed inline, while active web content is always downloaded.",
)
@require_permission("threads", "read", owner_check=True)
async def get_artifact(thread_id: str, path: str, request: Request, download: bool = False) -> Response:
    """按路径获取 artifact 文件。

    该端点会自动检测文件类型并返回合适的 Content-Type。
    使用 `download` 查询参数可强制下载非活动内容的文件。

    Args:
        thread_id: 线程 ID。
        path: 带虚拟前缀的 artifact 路径（例如 mnt/user-data/outputs/file.txt）。
        request: FastAPI 请求对象（自动注入）。

    Returns:
        以 FileResponse 形式返回的文件内容，并带有合适的 Content-Type：
        - 活动内容（HTML/XHTML/SVG）：作为下载附件返回
        - 文本文件：以正确的 MIME 类型返回纯文本
        - 二进制文件：内联展示，可选择下载

    Raises:
        HTTPException:
            - 400 路径无效或不是文件
            - 403 访问被拒绝（检测到路径穿越）
            - 404 文件未找到

    Query Parameters:
        download (bool): 为 true 时，对原本以内联或纯文本方式返回的文件类型
            强制以附件形式下载。无论该标志如何，HTML/XHTML/SVG 活动内容
            一律以下载方式返回。

    Example:
        - 内联获取文本文件：`/api/threads/abc123/artifacts/mnt/user-data/outputs/notes.txt`
        - 下载文件：`/api/threads/abc123/artifacts/mnt/user-data/outputs/data.csv?download=true`
        - `.html`、`.xhtml`、`.svg` 等活动 Web 内容的 artifact 一律以下载方式返回
    """
    # 检查是否请求的是 .skill 压缩包内的文件（例如 xxx.skill/SKILL.md）
    if ".skill/" in path:
        # 在 ".skill/" 处拆分路径，得到 ZIP 文件路径和内部路径
        skill_marker = ".skill/"
        marker_pos = path.find(skill_marker)
        skill_file_path = path[: marker_pos + len(".skill")]  # 例如 "mnt/user-data/outputs/my-skill.skill"
        internal_path = path[marker_pos + len(skill_marker) :]  # 例如 "SKILL.md"

        actual_skill_path = resolve_thread_virtual_path(thread_id, skill_file_path)

        if not actual_skill_path.exists():
            raise HTTPException(status_code=404, detail=f"Skill file not found: {skill_file_path}")

        if not actual_skill_path.is_file():
            raise HTTPException(status_code=400, detail=f"Path is not a file: {skill_file_path}")

        # 从 .skill 压缩包中提取文件
        content = _extract_file_from_skill_archive(actual_skill_path, internal_path)
        if content is None:
            raise HTTPException(status_code=404, detail=f"File '{internal_path}' not found in skill archive")

        # 根据内部文件确定 MIME 类型
        mime_type, _ = mimetypes.guess_type(internal_path)
        # 添加缓存头以避免重复解压 ZIP（缓存 5 分钟）
        cache_headers = {"Cache-Control": "private, max-age=300"}
        download_name = Path(internal_path).name or actual_skill_path.stem
        if download or mime_type in ACTIVE_CONTENT_MIME_TYPES:
            return Response(content=content, media_type=mime_type or "application/octet-stream", headers=_build_attachment_headers(download_name, cache_headers))

        if mime_type and mime_type.startswith("text/"):
            return PlainTextResponse(content=content.decode("utf-8"), media_type=mime_type, headers=cache_headers)

        # 对看似文本的未知类型默认按纯文本处理
        try:
            return PlainTextResponse(content=content.decode("utf-8"), media_type="text/plain", headers=cache_headers)
        except UnicodeDecodeError:
            return Response(content=content, media_type=mime_type or "application/octet-stream", headers=cache_headers)

    actual_path = resolve_thread_virtual_path(thread_id, path)

    logger.info(f"Resolving artifact path: thread_id={thread_id}, requested_path={path}, actual_path={actual_path}")

    if not actual_path.exists():
        raise HTTPException(status_code=404, detail=f"Artifact not found: {path}")

    if not actual_path.is_file():
        raise HTTPException(status_code=400, detail=f"Path is not a file: {path}")

    mime_type, _ = mimetypes.guess_type(actual_path)

    if download:
        return FileResponse(path=actual_path, filename=actual_path.name, media_type=mime_type, headers=_build_attachment_headers(actual_path.name))

    # 对活动内容类型始终强制下载，防止用户打开生成的 artifact 时
    # 在应用源（origin）中执行脚本。
    if mime_type in ACTIVE_CONTENT_MIME_TYPES:
        return FileResponse(path=actual_path, filename=actual_path.name, media_type=mime_type, headers=_build_attachment_headers(actual_path.name))

    if mime_type and mime_type.startswith("text/"):
        return PlainTextResponse(content=actual_path.read_text(encoding="utf-8"), media_type=mime_type)

    if is_text_file_by_content(actual_path):
        return PlainTextResponse(content=actual_path.read_text(encoding="utf-8"), media_type=mime_type)

    return Response(content=actual_path.read_bytes(), media_type=mime_type, headers={"Content-Disposition": _build_content_disposition("inline", actual_path.name)})
